# Site settings
title: Greenshot
email: getgreenshot@gmail.com
description: "Greenshot - a free screenshot tool optimized for productivity"
baseurl: ""
url: "http://greenshot.github.io/"
twitter_username: greenshot_tool
github_username: greenshot
facebook: Greenshot.Tool
googleplus: 108405649004966849465
openhub_project: greenshot
collections:
- faqs

# Build settings
markdown: redcarpet
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME', 'LICENSE']

gems:
  - jemoji

kramdown:
 input: GFM

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "hard_wrap"]
