# Site settings
title: Greenshot
email: getgreenshot@gmail.com
description: "Greenshot - a free screenshot tool optimized for productivity"
baseurl: ""
# TODO change URL to getgreenshot.org
url: "http://greenshot.github.io"
twitter_username: greenshot_tool
github_username: greenshot
facebook: Greenshot.Tool
googleplus: 108405649004966849465
openhub_project: greenshot

# TODO change to index,follow before going live, also remove robots.txt
metarobots: noindex, nofollow

collections:
  faqs:
    output: true
    permalink: /faq/:title/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/ 

defaults:
 -
  scope:
    path: "faq"
    type: "faqs"
  values:
    layout: "faq"

# Build settings
markdown: redcarpet
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME', 'LICENSE', '*.sh']

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
 input: GFM

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "hard_wrap"]
